[package]
name = "czui-core"
version = "0.0.1"
edition.workspace = true
license.workspace = true

[lib]
name = "czui_core"

[features]
test-support = ["dep:tempfile"]

[dependencies]
imara-diff.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
wait-timeout.workspace = true
libc.workspace = true
tempfile = { workspace = true, optional = true }

[dev-dependencies]
tempfile.workspace = true
